quarkus:
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  hibernate-orm:
    database:
      generation: drop-and-create
  swagger-ui:
    always-include: true
  http:
    cors:
      ~: true  # This enables CORS
      origins: http://localhost:5173
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: Accept,Authorization,Content-Type,X-Requested-With
      exposed-headers: Content-Disposition
      access-control-max-age: 24H
      access-control-allow-credentials: true

app:
  demo:
    test: "hello world"